"""initial migration

Revision ID: 22acff446b18
Revises: 
Create Date: 2026-06-12 16:01:31.846702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22acff446b18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_stack',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rol_name', sa.String(), nullable=True),
    sa.Column('feature', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol_name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('offer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_stack',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('stack_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['stack_id'], ['global_stack.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_stack',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_resource', sa.Integer(), nullable=True),
    sa.Column('id_stack', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_resource'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['id_stack'], ['global_stack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol_stack',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.Column('id_stack', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id'], ),
    sa.ForeignKeyConstraint(['id_stack'], ['global_stack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_stack',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_offer', sa.Integer(), nullable=True),
    sa.Column('id_stack', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_offer'], ['offer.id'], ),
    sa.ForeignKeyConstraint(['id_stack'], ['global_stack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_stack')
    op.drop_table('rol_stack')
    op.drop_table('resource_stack')
    op.drop_table('personal_stack')
    op.drop_table('offer')
    op.drop_table('users')
    op.drop_table('rol')
    op.drop_table('resource')
    op.drop_table('global_stack')
    # ### end Alembic commands ###
